app/config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from app import views, api
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from app.worker.tasks import scan_state

schema_view = get_schema_view(
    openapi.Info(
        title="Mobile Audit API",
        default_version='v1',
        description="Version 1 of the API",
        contact=openapi.Contact(email="pastorabanades@gmail.com"),
        license=openapi.License(name="GNU v3"),
    ),
    public=True,
)

# API router
router = routers.DefaultRouter()
router.register(r'app', api.ApplicationViewSet)
router.register(r'scan', api.ScanViewSet)
router.register(r'finding', api.FindingViewSet)
router.register(r'permission', api.PermissionViewSet)

# App paths
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('app/create', views.create_app, name='create_app'),
    path('app/<int:id>', views.app, name='app'),
    path('scan/<int:id>', views.scan, name='scan'),
    path('findings/', views.findings, name='findings'),
    path('findings/<int:scan_id>', views.findings, name='findings'),
    path('finding/create', views.create_finding, name='create_finding'),
    path('finding/create/<int:scan_id>', views.create_finding, name='create_finding'),
    path('finding/<int:id>', views.finding, name='finding'),
    path('finding/edit/<int:id>', views.edit_finding, name='edit_finding'),
    path('finding/file/<int:id>', views.finding_view_file, name='finding_view_file'),
    path('file/<int:id>', views.view_file, name='view_file'),
    path('scan/create', views.create_scan, name='create_scan'),
    path('scan/create/<int:app_id>', views.create_scan, name='create_scan'),
    path('scan/delete/<int:scan_id>', views.delete_scan, name='delete_scan'),
    path('patterns/', views.patterns, name="patterns"),
    path('permissions/', views.permissions, name="permissions"),
    path('malware/', views.malware, name="malware"),
    path('export/<int:id>', views.export, name="export"),
    path('update_virustotal/<int:scan_id>', views.update_virustotal, name="update_virustotal"),
    #path('admin/', admin.site.urls),
    path('accounts/login/', views.user_login, name="login"),
    path('accounts/register/', views.user_register, name="register"),
    path('accounts/logout/', views.user_logout, name='logout'),
    path('accounts/profile/', views.user_profile, name='profile'),
    path('api/v1/auth-token/', obtain_auth_token, name='api_token_auth'),
    path('api/v1/', include(router.urls)),
    path('scan_state/<int:id>', scan_state, name="scan_state"),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
    
]

app/models.py
from django.db import models
import os
from django.core.exceptions import ValidationError
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True)
    last_name = models.CharField(max_length=100, blank=True)
    email = models.EmailField(max_length=150)

    def __str__(self):
        return self.user.username

    @receiver(post_save, sender=User)
    def update_profile_signal(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()

def validate_file_extension(value):
    ext = os.path.splitext(value.name)[1]
    valid_extensions = ['.apk']
    if not ext.lower() in valid_extensions:
        raise ValidationError(u'Unsupported file extension.')

class Severity(models.TextChoices):
    CR = ('CR', 'Critical')
    HI = ('HI', 'High')
    ME = ('ME', 'Medium')
    LO = ('LO', 'Low')
    NO = ('NO', 'None')
    
    def __str__(self):
        return self.get_severity_display()

class Status(models.TextChoices):
    VF = ('VF', 'Verified')
    FP = ('FP', 'False Positive')
    TP = ('TP', 'True Positive')
    MI = ('MI', 'Mitigated')
    UK = ('UK', 'Unknown')
    TD = ('TD', 'To Do')

    def __str__(self):
        return self.get_status_display()

class Application(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255, blank=False)
    description = models.CharField(max_length=255, blank=False)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Scan(models.Model):
    id = models.AutoField(primary_key=True)
    app = models.ForeignKey(Application, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=True)
    apk = models.FileField(upload_to='apk/', blank=False, validators=[validate_file_extension])
    description = models.CharField(max_length=255, blank=False)
    defectdojo_id = models.IntegerField(blank=True, default=0)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.CharField(max_length=50,blank=True, null=True)
    progress = models.IntegerField(blank=True, null=True)
    findings = models.IntegerField(blank=True, null=True, default=0)
    apk_name = models.CharField(max_length=255, blank=True, null=True)
    file_size = models.CharField(max_length=255, blank=True, null=True)
    md5 = models.CharField(max_length=255, blank=True, null=True)
    sha1 = models.CharField(max_length=255, blank=True, null=True)
    sha256 = models.CharField(max_length=255, blank=True, null=True)
    package = models.CharField(max_length=255, blank=True, null=True)
    icon = models.TextField(blank=True, null=True)
    version_code = models.CharField(max_length=50, blank=True, null=True)
    version_name = models.CharField(max_length=50, blank=True, null=True)
    min_sdk_version = models.CharField(max_length=50, blank=True, null=True)
    max_sdk_version = models.CharField(max_length=50, blank=True, null=True)
    target_sdk_version = models.CharField(max_length=50, blank=True, null=True)
    effective_target_sdk_version = models.CharField(max_length=50, blank=True, null=True)
    manifest = models.TextField(blank=True, null=True)
    task = models.CharField(max_length=50, blank=True, null=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Cwe(models.Model):
    cwe = models.IntegerField(primary_key=True)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Risk(models.Model):
    risk = models.IntegerField(primary_key=True)
    description = models.TextField()
    reference = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Pattern(models.Model):
    id = models.AutoField(primary_key=True)
    default_cwe = models.ForeignKey(Cwe, on_delete=models.CASCADE)
    default_risk = models.ForeignKey(Risk, on_delete=models.CASCADE, null=True)
    default_name = models.TextField()
    default_description = models.TextField(blank=True)
    default_severity = models.CharField(
        max_length=10,
        choices=Severity.choices
    )
    default_mitigation = models.TextField(blank=True)
    pattern = models.TextField()
    active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Finding(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    type = models.ForeignKey(Pattern, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=512, blank=False)
    path = models.CharField(max_length=1024, blank=False)
    line_number = models.IntegerField(null=True)
    line = models.TextField()
    snippet = models.TextField()
    match = models.TextField(blank=True, null=True)
    status = models.CharField(
        max_length=50,
        choices=Status.choices
    )
    severity = models.CharField(
        max_length=10,
        choices=Severity.choices
    )
    description = models.TextField()
    mitigation = models.TextField(blank=True, null=True)
    cwe = models.ForeignKey(Cwe, on_delete=models.CASCADE)
    risk = models.ForeignKey(Risk, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    defectdojo_id = models.IntegerField(blank=True, default=0)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Activity(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    name = models.TextField()
    main = models.BooleanField(default=False)
    exported = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class PermissionType(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.TextField(unique=True)
    type = models.CharField(max_length=50)
    default_severity = models.CharField(
        max_length=10,
        choices=Severity.choices
    )
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Permission(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    permission = models.ForeignKey(PermissionType, on_delete=models.CASCADE)
    severity = models.CharField(
        max_length=10,
        choices=Severity.choices
    )
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Component(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    name = models.TextField()
    type = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class IntentFilter(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    name = models.TextField()
    action = models.TextField()
    component = models.ForeignKey(Component, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class Certificate(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    version = models.CharField(max_length=10, blank=True)
    sha1 = models.CharField(max_length=255, blank=True)
    sha256 = models.CharField(max_length=255, blank=True)
    issuer = models.TextField(blank=True)
    subject = models.TextField(blank=True)
    hash_algorithm = models.TextField(blank=True)
    signature_algorithm = models.TextField(blank=True)
    serial_number = models.TextField(blank=True)
    contents =  models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class String(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    finding = models.ForeignKey(Finding, on_delete=models.CASCADE)
    type = models.CharField(max_length=255)
    value = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class DatabaseInfo(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    table = models.CharField(max_length=255)
    info = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True, null=True)
    updated_on = models.DateTimeField(auto_now=True, null=True)

class File(models.Model):
    id = models.AutoField(primary_key=True)
    scan = models.ForeignKey(Scan, on_delete=models.CASCADE)
    type = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=255)
    created_on = models.DateTimeField(auto_now_add=True, null=True)

app/templates/app.html
{% extends 'base.html' %} {% load fontawesome_5 %} {% load static %} {% block content %}
{% if app %}
<div class="card">
    <div class="card-body">
        <h4 class="card-title">App</h4>
        <table class="table table-striped table-bordered">
            <tr>
                <th>App name</th>
                <td>{{ app.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ app.description }}</td>
            </tr>
            <tr>
                <th>Created by</th>
                <td>{{ app.user }}</td>
            </tr>
        </table>
    </div>
</div>
<br>
<div id="chart" style="height:450px">
    <h5>Evolution</h4>
    <link rel="stylesheet" type="text/css" href="{% static 'chartjs/Chart.min.css' %}">
    <canvas id="myChart" width="400" height="400"></canvas>
</div>
<br>
<h5>Scans</h5>
<a href="{% url 'create_scan' app_id=app.id %}" class="btn btn-outline-success">New Scan</a> {% if scans %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th style="width: 5%;">ID</th>
            <th style="width: 10%;">Description</th>
            <th style="width: 10%;">Apk name</th>
            <th style="width: 5%;">Version</th>
            <th style="width: 10%;">Created On</th>
            <th style="width: 10%;">Status</th>
            <th style="width: 5%;">Progress</th>
            {% if settings.VIRUSTOTAL_ENABLED %}
            <th style="width: 10%;">VT</th>
            {% endif %}
            <th style="width: 10%;">Findings</th>
            <th style="width: 30%;">By Severity</th>
            {% if user.is_authenticated %}
            <th style="width: 6%;">Delete</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for scan in scans %}
        <tr>
            <td><a class="btn btn-outline-secondary btn-round" href="{% url 'scan' id=scan.id %}"> {{ scan.id }}</a></td>
            <td>{{ scan.description }} </td>
            <td>{{ scan.apk_name }} </td>
            <td>{{ scan.version_code }}</td>
            <td>{{ scan.created_on }}</td>
            <td>{{ scan.status }}</td>
            <td>{{ scan.progress }} %</td>
            {% for id, scan_data in scans_data.items %} {% if id == scan.id %} {% if settings.VIRUSTOTAL_ENABLED %} {% if scan_data.antivirus.malicious > 0 %}
            <td> {% fa5_icon 'shield-alt' color='red' %} {{ scan_data.antivirus.malicious }}</td>
            {% else %}
            <td> {% fa5_icon 'shield-alt' color='green' %} {{ scan_data.antivirus.malicious }}</td>
            {% endif %} {% endif %}
            <td><a href="{% url 'findings' scan_id=scan.id %}" target="_blank" rel="noopener noreferrer">{{ scan.findings }}</a></td>
            <td>
                <table class="table table-borderless">
                    {% for severity, number in scan_data.findings.items %}
                    <tr>
                        <th> {{ severity }} </th>
                        {% if severity == 'Critical' %}
                        <td>{% fa5_icon 'exclamation-circle' color='black' %} {{ number }} </td>
                        {% elif severity == 'High' %}
                        <td>{% fa5_icon 'exclamation-circle' color='red' %} {{ number }} </td>
                        {% elif severity == 'Medium'%}
                        <td>{% fa5_icon 'exclamation-circle' color='orange' %} {{ number }}</td>
                        {% elif severity == 'Low' %}
                        <td>{% fa5_icon 'exclamation-circle' color='blue' %} {{ number }}</td>
                        {% else %}
                        <td>{% fa5_icon 'check-circle' color='green' %} {{ number }}</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </table>
            </td>
            <td>
                <form action="{% url 'delete_scan' scan.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <button type="submit" class="delete-scan btn btn-danger">{% fa5_icon 'trash-alt' color='white' %}</button>
                </form>
            </td>
            {% endif %} {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<script type="text/javascript">
    function fade_alerts() {
        alerts = document.getElementsByClassName("alert");
        var i = alerts.length;
        for (let elem of alerts) {
            i--;
            time = 3250+(1000*i);
            setTimeout(function() {
                $(elem).fadeOut("slow");
            }, time);
        }
    }
    window.addEventListener('DOMContentLoaded', (event) => {
        fade_alerts();
    });
    $(document).ready(function() {
        $('.delete-scan').on('click', function(e) {
            if (!confirm('Do you really want to delete the scan?')) {
                e.preventDefault();
            }
        });
        
    });
</script>
{% endif %} 
<script type="text/javascript" charset="utf8" src="{% static 'chartjs/Chart.min.js' %}"></script>
<script>
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: {{ chart_labels|safe }},
        datasets: [{
            label: 'Findings',
            data: {{ chart_data|safe }},
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        responsive: false,
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
</script>
{% endif %} {% endblock %}

app/templates/create_app.html
{% extends 'base.html' %} {% load widget_tweaks %} {% load fontawesome_5 %} {% block content %}
<button class="btn btn-sm btn-outline-secondary" onclick="window.history.back()">{% fa5_icon 'chevron-left' %} Back </button>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label> {% render_field field class="form-control" placeholder=field.label %} {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error | escape }}</strong>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-primary">Create</button>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success">
        <strong>{{ message | escape }}</strong>
    </div>
    {% endfor %}
</ul>
<script type="text/javascript">
    function fade_alerts() {
        alerts = document.getElementsByClassName("alert");
        var i = alerts.length;
        for (let elem of alerts) {
            i--;
            time = 3250+(1000*i);
            setTimeout(function() {
                $(elem).fadeOut("slow");
            }, time);
        }
    }
    window.addEventListener('DOMContentLoaded', (event) => {
        fade_alerts();
    });
</script>
{% endif %}
{% endblock %}

app/templates/create_finding.html
{% extends 'base.html' %} {% load widget_tweaks %} {% load fontawesome_5 %} {% block content %}
<button class="btn btn-sm btn-outline-secondary" onclick="window.history.back()">{% fa5_icon 'chevron-left' %} Back </button>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label> {% render_field field class="form-control" placeholder=field.label %} {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error | escape }}</strong>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-info">Create</button>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success">
        <strong>{{ message | escape }}</strong>
    </div>
    {% endfor %}
</ul>
{% endif %} {% if finding %}
<a class="btn btn-sm btn-outline-warning" href="{% url 'finding' id=finding %}">See finding {% fa5_icon 'chevron-right' %}</a>{% if scan %}
<a class="btn btn-sm btn-outline-info" href="{% url 'create_finding' scan_id=scan %}">Create other finding {% fa5_icon 'redo-alt' %}</a> {% else %}
<a class="btn btn-sm btn-outline-info" href="{% url 'create_finding' %}">Create other finding {% fa5_icon 'redo-alt' %}</a> {% endif %} {% endif %} 

<script type="text/javascript">
    function fade_alerts() {
        alerts = document.getElementsByClassName("alert");
        var i = alerts.length;
        for (let elem of alerts) {
            i--;
            time = 3250+(1000*i);
            setTimeout(function() {
                $(elem).fadeOut("slow");
            }, time);
        }
    }
    window.addEventListener('DOMContentLoaded', (event) => {
        fade_alerts();
    });
</script>

{% endblock %}

app/templates/create_scan.html
{% extends 'base.html' %} {% load widget_tweaks %} {% load fontawesome_5 %} {% block content %}
<button class="btn btn-sm btn-outline-secondary" onclick="window.history.back()">{% fa5_icon 'chevron-left' %} Back </button>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% for field in form.visible_fields %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label> {% render_field field class="form-control" placeholder=field.label %} {% for error in field.errors %}
        <div class="alert alert-danger">
            <strong>{{ error | escape }}</strong>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-outline-success">Upload</button>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success">
        <strong>{{ message | escape }}</strong>
    </div>
    {% endfor %}
</ul>
{% endif %} 
<script type="text/javascript">
    function fade_alerts() {
        alerts = document.getElementsByClassName("alert");
        var i = alerts.length;
        for (let elem of alerts) {
            i--;
            time = 3250+(1000*i);
            setTimeout(function() {
                $(elem).fadeOut("slow");
            }, time);
        }
    }
    window.addEventListener('DOMContentLoaded', (event) => {
        fade_alerts();
    });
</script>  
{% endblock %}

app/templates/patterns.html
{% extends 'base.html' %} {% load fontawesome_5 %} {% block content %}
<button class="btn btn-sm btn-outline-secondary" onclick="window.history.back()">{% fa5_icon 'chevron-left' %} Back </button> {% if patterns %}
<br>
<form action="{% url 'patterns' %}" method="post" enctype="multipart/form-data">
    <div class="btn-group mr-2">
        <button class="btn btn-sm btn-outline-primary dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Bulk Edit
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu" id="bulk_edit">
            <li style="margin: 15px;">
                <label style="display: block" for="status">Status</label>
                <select name="status" id="status">
                        <option value="">Choose Status</option>
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                    </select>
                <input type="submit" name="edit_patterns" class="btn btn-sm btn-primary" value="Edit Patterns">
            </li>
        </ul>
    </div>
    {% csrf_token %}
    <table id="patterns" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th style="width: 3%;"><input id="id_select_all" name="select_all" type="checkbox" /></th>
                <th style="width: 6%;">ID</th>
                <th style="width: 10%;">Pattern</th>
                <th style="width: 25%;">Description</th>
                <th style="width: 25%;">Mitigation</th>
                <th style="width: 6%;">Severity</th>
                <th style="width: 6%;">Active</th>
                <th style="width: 6%;">Status</th>
                <th style="width: 7%;">CWE</th>
                <th style="width: 7%;">Risk</th>
            </tr>
        </thead>
        <tbody>
            {% for pattern in patterns %}
            <tr>
                <td><input id="{{ pattern.id }}" class="pattern" name="{{ pattern.id }}" type="checkbox" /></td>
                <td>{{ pattern.id }}</td>
                <td>{{ pattern.default_name }}</td>
                <td>{{ pattern.default_description }}</td>
                <td>{{ pattern.default_mitigation }}</td>
                <td>{{ pattern.get_default_severity_display }}</td>
                {% if pattern.active %}
                <td>Yes</td>
                <td>{% fa5_icon 'check-circle' color='green' %}</td>
                {% else %}
                <td>No</td>
                <td>{% fa5_icon 'exclamation-circle' color='red' %}</td>
                {% endif %}
                <td><a class="link" href="https://cwe.mitre.org/data/definitions/{{finding.cwe.cwe}}.html" target="_blank" rel="noopener noreferrer">{{ pattern.default_cwe.cwe }} </a></td>
                <td><a class="link" href="{{ pattern.default_risk.reference }}" target="_blank" rel="noopener noreferrer">M{{ pattern.default_risk.risk }} </a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</form>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success">
        <strong>{{ message | escape }}</strong>
    </div>
    {% endfor %}
</ul>
{% endif %}
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_select_all').on('click', function() {
            $('.pattern').prop('checked', this.checked);
        });
        $('.dropdown-menu').click(function(e) {
            e.stopPropagation();
        });
        $("#patterns").DataTable()
    });
</script>
{% endif %} {% endblock %}

app/templates/permissions.html
{% extends 'base.html' %} {% load fontawesome_5 %} {% block content %}
<button class="btn btn-sm btn-outline-secondary" onclick="window.history.back()">{% fa5_icon 'chevron-left' %} Back </button>

<table id="permissions" class="table table-striped table-bordered table-order">
    <thead>
        <tr>
            <th style="width: 6%;">ID</th>
            <th style="width: 30%;">Permission</th>
            <th style="width: 10%;">Type</th>
            <th style="width: 6%;">Severity</th>
            <th style="width: 6%;"></th>
        </tr>
    </thead>
    <tbody>
        {% for permission in permissions %}
        <tr>
            <td><a href="">{{ permission.id }}</a></td>
            <td>{{ permission.name }}</td>
            <td>{{ permission.type }}</td>
            <td>{{ permission.get_default_severity_display }}</td>
            {% if permission.default_severity == 'HI' %}
            <td>{% fa5_icon 'exclamation-circle' color='red' %}</td>
            {% elif permission.default_severity == 'ME' %}
            <td>{% fa5_icon 'exclamation-circle' color='orange' %}</td>
            {% else %}
            <td>{% fa5_icon 'check-circle' color='green' %}</td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>
<script type="text/javascript">
    $(document).ready(function() {
        $('.table-order').each(function() {
            try {
                $(this).DataTable({
                    paging: false
                });
            } catch (error) {
                console.log(this)
            }
        });
    });
</script>
{% endblock %}